version: '3.6'

services:
  nats:
    image: nats-streaming:latest
    entrypoint:
      - /nats-streaming-server
      - -cid
      - amethyst-cluster
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    restart: always
    tty: true
    networks:
      - main

  mongodb:
    image: mongo:5.0
    container_name: mongodb-moleculer-example
    ports:
      - 27017:27017
    volumes:
      - ./.persistence_store/mongodb/db-data:/data/db
      - ./.persistence_store/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=moleculer-example
    networks:
      - main
    restart: unless-stopped


networks:
  main:
    driver: bridge

